USE [master]
GO

/****** Object:  Database [dbOregonLibrary]    Script Date: 3/5/2017 11:27:30 AM ******/
CREATE DATABASE [dbOregonLibrary]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'dbOregonLibrary', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\dbOregonLibrary.mdf' , SIZE = 3136KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'dbOregonLibrary_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\dbOregonLibrary_log.ldf' , SIZE = 784KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [dbOregonLibrary] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [dbOregonLibrary].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [dbOregonLibrary] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [dbOregonLibrary] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [dbOregonLibrary] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [dbOregonLibrary] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [dbOregonLibrary] SET ARITHABORT OFF 
GO

ALTER DATABASE [dbOregonLibrary] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [dbOregonLibrary] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [dbOregonLibrary] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [dbOregonLibrary] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [dbOregonLibrary] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [dbOregonLibrary] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [dbOregonLibrary] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [dbOregonLibrary] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [dbOregonLibrary] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [dbOregonLibrary] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [dbOregonLibrary] SET  ENABLE_BROKER 
GO

ALTER DATABASE [dbOregonLibrary] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [dbOregonLibrary] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [dbOregonLibrary] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [dbOregonLibrary] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [dbOregonLibrary] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [dbOregonLibrary] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [dbOregonLibrary] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [dbOregonLibrary] SET RECOVERY FULL 
GO

ALTER DATABASE [dbOregonLibrary] SET  MULTI_USER 
GO

ALTER DATABASE [dbOregonLibrary] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [dbOregonLibrary] SET DB_CHAINING OFF 
GO

ALTER DATABASE [dbOregonLibrary] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [dbOregonLibrary] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [dbOregonLibrary] SET  READ_WRITE 
GO

